### ISSUE TITLE
Initial gear system

### ISSUE THREAD

**Issue by antarktikali** [tosh823/banana-fgjx#3]
We would have two slots on the screen for rotating gears. The rotating gear slots are located on the lower left side of the screen.

First slot is to the left and it has a gear attached to it with a fixed size and rotation speed. The player can select the gear that would be attached to the second slot.

There are 3 different sizes of gears that the player can select to place on the second slot. They are represented as icons on the lower right side of the screen, and when the player clicks one of them, the second gear slot is updated with that gear.

Since gears have different sizes, the pivot of the second gear slot has to be adjusted horizontally depending on the size of the gear.

The teeth number for the gears are as follows:
Slot 1:
  fixed gear: 8
Slot 2:
  first user selected gear: 8 (rotates the same speed as the fixed, fast speed movement)
  second user selected gear: 12 (rotates 1.5 times slower than fixed, normal speed movement)
  third user selected gear: 16 (rotates 2 times slower than fixed, slow speed movement)

@onurozuduru @tosh823 @eldraak  please propose any changes and approve this initial proposal 🤣

**Comment by onurozuduru** [comment]
@antarktikali can you add a digram.

**Comment by antarktikali** [comment]
@onurozuduru nope 👎

**Comment by onurozuduru** [comment]
We need a can-do attitude in this company.

**Comment by onurozuduru** [comment]
Good job people :) @antarktikali @tosh823 @eldraak
